### ISSUE TITLE
User Auth Checklist

### ISSUE THREAD

**Issue by mikolas2788** [jzhou45/Metabook#8]
# User Auth
## Functionality
- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation
### Before Login
- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [ ] Errors should display for both `/signup` and `/login`.
- [ ] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can’t sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user
### After Login
- [ ] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

**Comment by mikolas2788** [comment]
- Random frontend routes, /login, /signup, etc should redirect or display 404
- Have /signup display error messages in same styling as /login
- Consider whether to clear login errors when opening sign up modal
- Consider that when rendering login errors --> then opening signup modal --> rendering signup errors --> closing modal --> both errors persist even when reopening signup modal.
- When attempting to sign up with a pre-existing user, resolve bug in console and properly render error message
